### ISSUE TITLE
Image upload option not available for Gemma3

### ISSUE THREAD

**Issue by WaelShaikh** [JHubi1/ollama-app#83]
### Requirements

- [x] I have searched the issues of this repository and believe that this is not a duplicate
- [x] I have confirmed this bug exists on the latest version of the app

### Platform

Android

### Description

I was trying to upload an image to gemma3:4b which is multimodal but the option to upload images was not present.

### Steps to reproduce

1. Load any gemma3 model other than 1B (since 1B is not multimodal)
2. Load the chat interface

### Expected behavior

I expected to see a button to upload images

### Actual behavior

There was option to upload images

**Comment by Samuele458** [comment]
No updates on this? The problem is still here, and no new releases in months (last is from 2024)

**Comment by JHubi1** [comment]
There's no unified way of detecting vision or multimodal models through Ollama's API right now, so I'm unable to solve this issue for now

**Comment by Samuele458** [comment]
> There's no unified way of detecting vision or multimodal models through Ollama's API right now, so I'm unable to solve this issue for now

Yes, I understand. However, being for me necessary to find a way for running Gemma3 on mobile, with multimodal support, I've implemented by myself a quick fix/workaround.

This is my fork:
https://github.com/Burneeble/ollama-app

(for anyone wondering, in the Actions tab you'll find the updated apk in the latest successful build workflow).

My goal was just to find a quick fix, however if you want I can even open the PR.

**Comment by JHubi1** [comment]
Ollama [v0.6.4](https://github.com/ollama/ollama/releases/tag/v0.6.4) includes the necessary information in the API response now. Will add this soon.

**Comment by Silent-Hunter** [comment]
Is there any sort of estimate on when this fix will be available? It'd be mighty useful!

**Comment by JHubi1** [comment]
Will implement when https://github.com/davidmigloz/langchain_dart/pull/690 is resolved.

**Comment by JHubi1** [comment]
It's now implemented. I'll maybe still rework it though.

**Comment by TheShovel** [comment]
i just built and tested it, and the button still doesnt show up

**Comment by JHubi1** [comment]
> i just built and tested it, and the button still doesnt show up

Yes, it has a type match issue (`details.capabilities` is not a list of strings but of a capability enum, so match is never true). Didn't test before pushing. I did a quick fix that should fix that in https://github.com/JHubi1/ollama-app/commit/3759d32049771096b172b99400edae6d4f1a2557. You may retry with a new build.

I'm working on a new version of the app right now that isn't using this code anymore. Just teasing a little.
